config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'browse', to: 'posts#browse', as: :browse_posts

  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through 
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: 'posts#index'
  
  resources :posts do 
    resources :comments
    
    member do 
      get 'like'
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile 
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target-id="bs-navbar-collapse-1" data-toggle="collapse"></button>
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= render 'notifications/notification_dropdown' %>
          </li>
          <li>
            <%= link_to "New Post", new_post_path %>
          </li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to "Edit Registration", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "Browse Posts", browse_posts_path %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>